 # -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'takePicScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_bgWidget(object):
    def setupUi(self, bgWidget):
        bgWidget.setObjectName("bgWidget")
        bgWidget.resize(600, 400)
        bgWidget.setStyleSheet("QWidget#bgWidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.369, x2:1, y2:0.756, stop:0 rgba(237, 66, 100, 255), stop:1 rgba(255, 237, 188, 255));\n"
"}")
        self.takePic = QtWidgets.QPushButton(bgWidget)
        self.takePic.setGeometry(QtCore.QRect(410, 170, 170, 40))
        self.takePic.setStyleSheet("border-radius: 20px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(57, 174, 169);")
        self.takePic.setObjectName("takePic")
        self.label = QtWidgets.QLabel(bgWidget)
        self.label.setGeometry(QtCore.QRect(20, 70, 320, 240))
        self.label.setText("")
        self.label.setObjectName("label")
        self.error = QtWidgets.QLabel(bgWidget)
        self.error.setGeometry(QtCore.QRect(230, 10, 121, 31))
        self.error.setStyleSheet("color: red;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.error.setText("")
        self.error.setObjectName("error")
        self.nameInput = QtWidgets.QLineEdit(bgWidget)
        self.nameInput.setGeometry(QtCore.QRect(420, 120, 142, 30))
        self.nameInput.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(0, 0, 0, 0);")
        self.nameInput.setObjectName("nameInput")
        self.return_2 = QtWidgets.QPushButton(bgWidget)
        self.return_2.setGeometry(QtCore.QRect(410, 220, 170, 40))
        self.return_2.setStyleSheet("border-radius: 20px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(57, 174, 169);")
        self.return_2.setObjectName("return_2")
        self.nameLabel = QtWidgets.QLabel(bgWidget)
        self.nameLabel.setGeometry(QtCore.QRect(420, 100, 150, 20))
        self.nameLabel.setObjectName("nameLabel")

        self.retranslateUi(bgWidget)
        QtCore.QMetaObject.connectSlotsByName(bgWidget)

    def retranslateUi(self, bgWidget):
        _translate = QtCore.QCoreApplication.translate
        bgWidget.setWindowTitle(_translate("bgWidget", "Dialog"))
        self.takePic.setText(_translate("bgWidget", "take picture"))
        self.return_2.setText(_translate("bgWidget", "return"))
        self.nameLabel.setText(_translate("bgWidget", "enter your name:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    bgWidget = QtWidgets.QDialog()
    ui = Ui_bgWidget()
    ui.setupUi(bgWidget)
    bgWidget.show()
    sys.exit(app.exec_())

#         pyuic5 -x takePicScreen.ui -o takePicScreen.py
